#!/bin/sh

set -eu

redbean="redbean.com"

if ! test -e "$redbean"; then
  #curl https://redbean.dev/redbean-2.2.com -o "$redbean"
  # The next version supports Linux ARM:
  curl https://cosmo.zip/pub/cosmos/bin/redbean -o "$redbean"
fi
#echo "db8fc7cc5a7703b7ccb830a366eb69e728fc7892fd3ecc093c089d837aa5b91b $redbean" | sha256sum -c

exe="$(pwd)/planning-poker.exe"
cp "$redbean" "$exe"

chmod +wx "$exe"
cd ./src
zip "$exe" $(find . -mindepth 1)
